[package]
name = "bevy_simplesave"
# TODO: to 0.1.0
version = "0.0.4"
edition = "2024"
description = "A small, dependency-light crate for saving Bevy Resources to .ron files"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unclepomedev/bevy_simplesave"
readme = "README.md"
keywords = ["bevy", "save", "ron", "persistence"]
categories = ["game-development"]

[dependencies]
serde = { version = "1", features = ["derive"] }
ron = "0.12"
directories = "6.0"
# TODO: to 0.20, 0.1.0
bevy_ecs = { version = "0.20.0-rc.1", default-features = false, features = ["std"] }
bevy_app = { version = "0.20.0-rc.1", default-features = false, features = ["std"] }
bevy_simplesave_derive = { path = "bevy_simplesave_derive", version = "0.0.4" }
tempfile = "3"

[workspace]
members = [".", "bevy_simplesave_derive"]
