[package]
name = "bevy_simplesave"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
ron = "0.12"
directories = "6.0"
bevy_ecs = { version = "0.19", default-features = false, features = ["std"] }
bevy_app = { version = "0.19", default-features = false, features = ["std"] }
tempfile = "3"

[dev-dependencies]
