[package]
name = "bevy_simplesave_derive"
version = "0.0.3"
edition = "2024"
description = "Derive macro for bevy_simplesave"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unclepomedev/bevy_simplesave"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3", features = ["full"] }
quote = "1"
proc-macro2 = "1"
